"""
backend/models/roadmap.py
Weekly learning roadmap generated by the AI agent per user + target role.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from models.database import Base


class Roadmap(Base):
    __tablename__ = "roadmaps"

    # ── Primary key ──────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # ── Foreign key ───────────────────────────────────────────────────────────
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Roadmap metadata ──────────────────────────────────────────────────────
    target_role: Mapped[str] = mapped_column(String(100), nullable=False)

    # ── Plan structure ────────────────────────────────────────────────────────
    # Example:
    # {
    #   "weeks": [
    #     {"week": 1, "focus": "Arrays & Hashing", "topics": ["Two Sum", "Valid Anagram"]},
    #     {"week": 2, "focus": "Two Pointers", "topics": [...]}
    #   ]
    # }
    plan: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # ── State ─────────────────────────────────────────────────────────────────
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        default=datetime.utcnow,
        server_default=func.now(),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "User",
        back_populates="roadmaps",
    )

    def __repr__(self) -> str:
        return f"<Roadmap id={self.id} user_id={self.user_id} role={self.target_role}>"